[package]
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]
description = "Rust wrapper around the libcryptsetup library, allowing manipulation of LUKS devices in Linux"
homepage = "https://gitlab.com/solidninja/cryptsetup-rs"
license = "LGPL-3.0"
name = "cryptsetup-rs"
version = "0.2.1"
edition = "2018"

[dependencies]
errno = "0.2.4"
libc = "0.2.62"
log = "0.4.8"

[dependencies.blkid-rs]
path = "blkid-rs"
version = "0.1.2"

[dependencies.libcryptsetup-sys]
path = "libcryptsetup-sys"
version = "0.1.2"

[dependencies.uuid]
features = ["v4"]
version = "0.7.4"

[dev-dependencies]
env_logger = "0.7.0"
expectest = "0.11.0"
tempdir = "0.3.7"

[lib]
name = "cryptsetup_rs"
